platform :ios, '17.0'
use_frameworks! :linkage => :static

project 'Playarr.xcodeproj'

target 'PlayarrApp' do
  pod 'google-cast-sdk', '= 4.8.6'

  target 'PlayarrAppTests' do
    inherit! :search_paths
  end
end
