apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: playarr
  app.kubernetes.io/managed-by: kustomize

resources:
  - statefulset.yaml
  - service.yaml
  - configmap.yaml

images:
  - name: ghcr.io/playarr/playarr
    newTag: "0.1.0"
