apiVersion: v1
kind: Service
metadata:
  name: playarr
  labels:
    app.kubernetes.io/name: playarr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8484
    - name: metrics
      port: 9090
      targetPort: metrics
  selector:
    app.kubernetes.io/name: playarr
