apiVersion: v1
kind: Service
metadata:
  name: playarr-api
  labels:
    app.kubernetes.io/name: playarr
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8484
    - name: metrics
      port: 9090
      targetPort: metrics
  selector:
    app.kubernetes.io/name: playarr
    app.kubernetes.io/component: api
---
apiVersion: v1
kind: Service
metadata:
  name: playarr-worker
  labels:
    app.kubernetes.io/name: playarr
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 8484
      targetPort: 8484
    - name: metrics
      port: 9090
      targetPort: metrics
  selector:
    app.kubernetes.io/name: playarr
    app.kubernetes.io/component: worker
