apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "streamarr.configMapName" . }}
  labels:
    {{- include "streamarr.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
