#!/usr/bin/env bash
# Fetches and builds Shaka Player for Vega, and installs it where the app loads it (src/vendor/shaka, git-ignored).
#
#   scripts/setup-shaka.sh            # ./src/vendor/shaka
#
# Amazon distributes Shaka Player for Vega as a patch set (shaka-rel-<version>.tar.gz) to apply to the upstream
# shaka-player release, not as an npm package, and its wrapper and polyfills carry Amazon's own licence, so none of it is
# committed here. This script downloads the archive (pinned by SHA-256), clones upstream Shaka at the matching tag,
# applies Amazon's patches, builds the library (debug name `compiled`, no UI) and copies the build and Amazon's polyfills
# into src/vendor/shaka. Needs git, python3, Java 21+ and node, and network access. Run it once before building the app;
# without it the app still builds and plays through the platform decoder where it can, and shows
# "Shaka Player for Vega is unavailable" for HLS.
set -euo pipefail

VERSION="4.16.13"
RELEASE="r1.2"
URL="https://amzndevresources.com/vega/media-player/shaka-rel-v${VERSION}-${RELEASE}-devices_scope.tar.gz"
SHA256="1c06ca1c8502680f2e41609f7feb7483b5a16a78ec670e71a17eb3813e17d120"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
work="${SHAKA_WORK_DIR:-$root/.cache/shaka}"
dest="$root/src/vendor/shaka"
for tool in git python3 java node curl; do command -v "$tool" >/dev/null || { echo "setup-shaka: $tool is required" >&2; exit 1; }; done

mkdir -p "$work"
archive="$work/shaka-rel-${VERSION}-${RELEASE}.tar.gz"
if [ ! -f "$archive" ]; then curl -fsSL -o "$archive" "$URL"; fi
echo "$SHA256  $archive" | sha256sum -c - >/dev/null || { echo "setup-shaka: checksum mismatch for $archive" >&2; rm -f "$archive"; exit 1; }

rm -rf "$work/rel" "$work/shaka-player"
mkdir -p "$work/rel"
tar -xzf "$archive" -C "$work/rel" 2>/dev/null
rel="$work/rel/shaka-rel"
git clone --quiet --branch "v${VERSION}" --depth 1 https://github.com/shaka-project/shaka-player.git "$work/shaka-player"
(
  cd "$work/shaka-player"
  git -c user.name=build -c user.email=build@localhost checkout -q -b "amz_${VERSION}"
  git -c user.name=build -c user.email=build@localhost am -3 -q "$rel"/shaka-patch/[0-9]*.patch
  python3 build/build.py --name compiled --mode debug --force +@complete -@ui
)

rm -rf "$dest"
mkdir -p "$dest/dist" "$dest/polyfills"
cp "$work/shaka-player/dist/shaka-player.compiled.debug.js" "$dest/dist/"
for file in Document Element TextDecoder W3CMedia Misc; do cp "$rel/src/polyfills/${file}Polyfill.ts" "$dest/polyfills/"; done
cat > "$dest/index.ts" <<'TS'
// @ts-nocheck
// Generated by scripts/setup-shaka.sh: installs Amazon's polyfills, then exposes Shaka as globalThis.shaka.
import Document from './polyfills/DocumentPolyfill';
import Element from './polyfills/ElementPolyfill';
import TextDecoderPolyfill from './polyfills/TextDecoderPolyfill';
import W3CMediaPolyfill from './polyfills/W3CMediaPolyfill';
import MiscPolyfill from './polyfills/MiscPolyfill';
import shaka from './dist/shaka-player.compiled.debug';

Document.install();
Element.install();
TextDecoderPolyfill.install();
W3CMediaPolyfill.install();
MiscPolyfill.install();
globalThis.shaka = shaka;
export default shaka;
TS
echo "Shaka Player ${VERSION} (Vega ${RELEASE}) installed in $dest"
