//! Shared secret-generation/hashing helpers for opaque device codes, user
//! codes, and refresh tokens. Centralized here so [`crate::device_flow`]
//! and [`crate::refresh`] don't each make their own (potentially
//! inconsistent) choice about how a token is generated or hashed.

use sha2::{Digest, Sha256};
use uuid::Uuid;

/// A high-entropy opaque token (256 bits, from two concatenated UUIDv4s
/// hex-encoded) suitable for a `device_code` or a refresh-token secret.
/// `Uuid::new_v4` draws from the OS CSPRNG, which is all the randomness a
/// bearer secret like this needs -- there's no reason to pull in a
/// dedicated `rand` dependency just to reformat the same underlying
/// entropy source.
pub(crate) fn opaque_token() -> String {
    format!("{}{}", Uuid::new_v4().simple(), Uuid::new_v4().simple())
}

/// SHA-256 hex digest, used to store refresh-token secrets at rest without
/// keeping the raw value around. A fast, unsalted hash is the right tool
/// here (unlike a password hash): the input is already high-entropy random
/// data generated by [`opaque_token`], not a human-chosen secret, so there
/// is nothing for an attacker holding the hash to dictionary-guess.
pub(crate) fn hash_token(raw: &str) -> String {
    hex::encode(Sha256::digest(raw.as_bytes()))
}

/// RFC 8628 `user_code` alphabet: short enough to type on a remote/TV
/// keyboard, drawn from a set that excludes visually-confusable characters
/// (`0`/`O`, `1`/`I`/`L`).
const USER_CODE_ALPHABET: &[u8] = b"ABCDEFGHJKMNPQRSTUVWXYZ23456789";

/// An 8-character user code split as `XXXX-XXXX`, e.g. `"WXYZ-2349"`.
pub(crate) fn user_code() -> String {
    // Two UUIDs give 32 bytes, comfortably more than the 8 symbols we map
    // through the alphabet below (the modulo bias this introduces is
    // negligible for a human-facing, short-lived, rate-limited code and
    // not worth pulling in a dedicated RNG crate to avoid).
    let a = Uuid::new_v4();
    let b = Uuid::new_v4();
    let bytes: Vec<u8> = a.as_bytes().iter().chain(b.as_bytes()).copied().collect();

    let mut code = String::with_capacity(9);
    for (i, byte) in bytes.iter().take(8).enumerate() {
        if i == 4 {
            code.push('-');
        }
        let symbol = USER_CODE_ALPHABET[(*byte as usize) % USER_CODE_ALPHABET.len()];
        code.push(symbol as char);
    }
    code
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn opaque_tokens_are_unique_and_long() {
        let a = opaque_token();
        let b = opaque_token();
        assert_ne!(a, b);
        assert_eq!(a.len(), 64);
    }

    #[test]
    fn hash_token_is_deterministic_and_distinct_per_input() {
        let raw = opaque_token();
        assert_eq!(hash_token(&raw), hash_token(&raw));
        assert_ne!(hash_token(&raw), hash_token(&opaque_token()));
    }

    #[test]
    fn user_code_has_expected_shape() {
        let code = user_code();
        assert_eq!(code.len(), 9);
        assert_eq!(code.chars().nth(4), Some('-'));
        assert!(code
            .chars()
            .filter(|c| *c != '-')
            .all(|c| USER_CODE_ALPHABET.contains(&(c as u8))));
    }
}
