#!/usr/bin/env bash
set -euo pipefail

# build.sh [debug|release]: compile the Playarr HarmonyOS NEXT HAP.
#
# Usage:
#   bash scripts/build.sh          # debug (default)
#   bash scripts/build.sh release  # also produces the .app bundle
#
# Requires `bash scripts/fetch-sdk.sh` to have run at least once (this
# script sources its output at $OHOS_SDK_CACHE/env.sh).
#
# Brief reference: implementation brief §7.3 "Tier 1", §10 R4.
#
# R4: no `hvigorw` wrapper script is vendored into this repo. Those
# wrapper scripts are normally generated by DevEco Studio, and the
# fallback the brief calls out is exactly what this script does: invoke
# the Command Line Tools' own `hvigorw` binary directly, once
# `<cli-tools>/hvigor/bin` is on PATH (fetch-sdk.sh's env.sh already put
# it there). Do not add a committed hvigorw/hvigorw.js/hvigorw.bat here.

MODE="${1:-debug}"
case "$MODE" in
    debug | release) ;;
    *)
        echo "Usage: build.sh [debug|release]" >&2
        echo "  got: '$MODE'" >&2
        exit 1
        ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

OHOS_SDK_CACHE="${OHOS_SDK_CACHE:-$HOME/.cache/ohos-sdk}"
ENV_FILE="$OHOS_SDK_CACHE/env.sh"

if [ ! -f "$ENV_FILE" ]; then
    echo "ERROR: $ENV_FILE not found." >&2
    echo "Run 'bash scripts/fetch-sdk.sh' first to download the SDK and Command Line Tools." >&2
    exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

if ! command -v hvigorw >/dev/null 2>&1; then
    echo "ERROR: hvigorw not found on PATH after sourcing $ENV_FILE." >&2
    echo "Check that \$OHOS_CLI_HOME/hvigor/bin/hvigorw exists (OHOS_CLI_HOME=${OHOS_CLI_HOME:-<unset>})." >&2
    exit 1
fi

# hvigor refuses to start without a user-level npmrc ("No npmrc file is matched in
# the current user folder") and resolves its own plugins (@ohos/hvigor,
# @ohos/hvigor-ohos-plugin) from the `@ohos` scope, which the public npm registry and the
# generic Huawei Cloud mirror do not serve; only the HarmonyOS registry does. Write the
# file when it is missing or lacks the scope; a developer's own settings are kept.
NPMRC="${NPM_CONFIG_USERCONFIG:-$HOME/.npmrc}"
if ! grep -qs '^@ohos:registry=' "$NPMRC"; then
    echo "==> npm: configuring the @ohos registry in $NPMRC" >&2
    {
        grep -qs '^registry=' "$NPMRC" || echo 'registry=https://repo.huaweicloud.com/repository/npm/'
        echo '@ohos:registry=https://repo.harmonyos.com/npm/'
    } >>"$NPMRC"
fi

echo "==> ohpm: setting registry and installing dependencies" >&2
ohpm config set registry https://ohpm.openharmony.cn/ohpm/
ohpm install --all

if command -v codelinter >/dev/null 2>&1; then
    echo "==> Running codelinter (official ArkTS linter: see brief §7.3 step 3)" >&2
    # This is the definitive ArkTS lint pass; it is strictly better than
    # Tier 0's lexical checks in scripts/checks/arkts.mjs and is expected
    # to fail the build on real errors, same as the hvigor step below.
    codelinter
else
    echo "WARNING: codelinter not found on PATH: skipping the official ArkTS lint pass." >&2
    echo "WARNING: 'just harmony-validate' already ran the Tier 0 lexical checks, but those are not a substitute for codelinter." >&2
fi

HVIGOR_ARGS=(--mode module -p module=entry@default -p product=default -p "buildMode=$MODE" --no-daemon --stacktrace)

echo "==> hvigorw assembleHap (buildMode=$MODE)" >&2
hvigorw assembleHap "${HVIGOR_ARGS[@]}"

if [ "$MODE" = "release" ]; then
    echo "==> hvigorw assembleApp (buildMode=$MODE)" >&2
    # assembleApp is a project-level task: `--mode module` hides it ("Task assembleApp was not found").
    hvigorw assembleApp -p product=default -p "buildMode=$MODE" --no-daemon --stacktrace
fi

echo "==> Build complete." >&2
echo "    Unsigned HAP: entry/build/default/outputs/default/entry-default-unsigned.hap" >&2
if [ "$MODE" = "release" ]; then
    echo "    App bundle:   build/outputs/default/*.app" >&2
fi
echo "    To sign:      bash scripts/sign.sh" >&2
echo "    To deploy:    HDC_TARGET=<serial> bash scripts/deploy.sh" >&2
