apiVersion: v2
name: playarr-dev
description: Playarr development web surfaces and Emissary routes
type: application
version: 0.3.0
appVersion: "dev"

home: https://github.com/ThomasMcFarlane/playarr
sources:
  - https://github.com/ThomasMcFarlane/playarr
