// Generated by scripts/gen-avatar-art.mjs from clients/shared/profile-avatars/presets.json. Do not edit by hand.
export type AvatarArtElement = {tag: 'circle' | 'path' | 'rect'; props: Record<string, string | number>};

export const PROFILE_AVATAR_ART: Record<string, readonly AvatarArtElement[]> = {
  astronaut: [
    {tag: 'circle', props: {cx:50,cy:42,r:29,fill:'#eef5ff'}},
    {tag: 'circle', props: {cx:50,cy:42,r:21,fill:'#21315f'}},
    {tag: 'path', props: {d:'M31 77c4-13 14-20 19-20s15 7 19 20',fill:'#eef5ff'}},
    {tag: 'circle', props: {cx:43,cy:39,r:3,fill:'#fff'}},
    {tag: 'circle', props: {cx:57,cy:39,r:3,fill:'#fff'}},
    {tag: 'path', props: {d:'M44 49c4 3 8 3 12 0',fill:'none',stroke:'#fff',strokeWidth:3,strokeLinecap:'round'}},
    {tag: 'path', props: {d:'M21 25l-7-6m65 6 7-6',stroke:'#d7e5ff',strokeWidth:4,strokeLinecap:'round'}},
  ],
  cat: [
    {tag: 'path', props: {d:'M24 37 18 15l25 13h14l25-13-6 22c8 7 12 17 10 28-3 17-18 25-36 25S17 82 14 65c-2-11 2-21 10-28Z',fill:'#ffe0bd'}},
    {tag: 'path', props: {d:'m24 28-2-8 11 6m43 2 2-8-11 6',fill:'#ef8c92'}},
    {tag: 'path', props: {d:'M32 52h8m20 0h8',stroke:'#4b3550',strokeWidth:5,strokeLinecap:'round'}},
    {tag: 'path', props: {d:'m46 62 4 3 4-3m-4 3v6',fill:'none',stroke:'#4b3550',strokeWidth:3,strokeLinecap:'round',strokeLinejoin:'round'}},
    {tag: 'path', props: {d:'M35 65 15 60m20 11-20 5m50-11 20-5m-20 11 20 5',stroke:'#fff2df',strokeWidth:2.5,strokeLinecap:'round'}},
  ],
  dinosaur: [
    {tag: 'path', props: {d:'m28 29-9-14 17 4 5-12 10 13 12-9 2 17c14 5 23 16 23 29 0 18-16 31-38 31S12 75 12 57c0-12 6-22 16-28Z',fill:'#bde78b'}},
    {tag: 'circle', props: {cx:38,cy:49,r:5,fill:'#254b45'}},
    {tag: 'circle', props: {cx:65,cy:49,r:5,fill:'#254b45'}},
    {tag: 'circle', props: {cx:39,cy:47,r:1.5,fill:'#fff'}},
    {tag: 'circle', props: {cx:66,cy:47,r:1.5,fill:'#fff'}},
    {tag: 'path', props: {d:'M38 66c8 7 17 7 25 0',fill:'none',stroke:'#254b45',strokeWidth:4,strokeLinecap:'round'}},
    {tag: 'path', props: {d:'m45 67 3 7 4-6 4 6 3-7',fill:'#fff'}},
  ],
  robot: [
    {tag: 'path', props: {d:'M50 20V9m0 0 7-5M50 9l-7-5',stroke:'#e8fbff',strokeWidth:4,strokeLinecap:'round'}},
    {tag: 'rect', props: {x:17,y:20,width:66,height:62,rx:17,fill:'#dff7f7'}},
    {tag: 'rect', props: {x:26,y:34,width:48,height:31,rx:10,fill:'#294263'}},
    {tag: 'circle', props: {cx:40,cy:49,r:5,fill:'#72e3d3'}},
    {tag: 'circle', props: {cx:60,cy:49,r:5,fill:'#72e3d3'}},
    {tag: 'path', props: {d:'M40 72h20',stroke:'#6a91a3',strokeWidth:4,strokeLinecap:'round'}},
    {tag: 'path', props: {d:'M17 43H9v18h8m66-18h8v18h-8',fill:'none',stroke:'#dff7f7',strokeWidth:6,strokeLinejoin:'round'}},
  ],
  pirate: [
    {tag: 'circle', props: {cx:50,cy:53,r:34,fill:'#f3c49e'}},
    {tag: 'path', props: {d:'M18 35c7-20 54-25 68 2-23-8-44-6-68-2Z',fill:'#802f4b'}},
    {tag: 'path', props: {d:'M21 31 12 17c15-4 29 1 38 11',fill:'#c84b58'}},
    {tag: 'circle', props: {cx:38,cy:52,r:4,fill:'#3a2935'}},
    {tag: 'path', props: {d:'M58 52h13m-7-8v16',stroke:'#3a2935',strokeWidth:4,strokeLinecap:'round'}},
    {tag: 'path', props: {d:'M53 44c9-5 19-3 25 4',fill:'none',stroke:'#3a2935',strokeWidth:4}},
    {tag: 'path', props: {d:'M39 68c9 7 19 7 27-1',fill:'none',stroke:'#7e3e3f',strokeWidth:4,strokeLinecap:'round'}},
  ],
  alien: [
    {tag: 'path', props: {d:'M50 10c25 0 39 17 35 39-4 21-22 39-35 43-13-4-31-22-35-43C11 27 25 10 50 10Z',fill:'#c7f0bd'}},
    {tag: 'path', props: {d:'M25 43c9-8 18-8 24 1-5 14-17 18-24-1Zm50 0c-9-8-18-8-24 1 5 14 17 18 24-1Z',fill:'#292949'}},
    {tag: 'circle', props: {cx:38,cy:45,r:2,fill:'#fff'}},
    {tag: 'circle', props: {cx:62,cy:45,r:2,fill:'#fff'}},
    {tag: 'path', props: {d:'M42 72c5 2 11 2 16 0',fill:'none',stroke:'#4b765d',strokeWidth:3,strokeLinecap:'round'}},
    {tag: 'circle', props: {cx:18,cy:20,r:3,fill:'#e8dcff'}},
    {tag: 'circle', props: {cx:83,cy:17,r:2,fill:'#e8dcff'}},
  ],
};
