export interface SignupInvite {
  /**
   * Every address this invite's issuing peer group answers to, priority-
   * ordered (each entry's `url`, `peer_node_id` dropped -- see
   * `PeerAddressBundle.addresses`, `backend/crates/streamarr-api/
   * src/admin_peer.rs`). For a standalone, ungrouped server this is always
   * a single-element list -- the "additive and inert for one node" rollout
   * invariant `docs/architecture/peer-groups.md` states at its top.
   * Deliberately a plain `string[]`, not node-attributed: sign-up
   * redemption works at any node in the group by design (accounts/policies
   * are synced, §3.7/Phase 2), so this type -- and every caller of
   * `parseSignupInvite` -- never needs to know which node a given address
   * came from.
   */
  serverUrls: string[];
  inviteToken: string;
}

/**
 * Parses the values carried by an administrator-generated QR/link, per
 * `docs/architecture/peer-groups.md` §6.1.
 *
 * Two query-param shapes are accepted for the server address(es):
 *
 * - `servers=` (current): a `PeerAddressBundle.addresses` JSON array of
 *   `{peer_node_id, url}` objects (`[{"peer_node_id": "...", "url":
 *   "https://a.example.com"}, ...]`), base64url-encoded with no padding.
 *   Only each entry's `url` is kept -- `peer_node_id` is dropped, since
 *   sign-up redemption works at any node in the group by design (see
 *   `SignupInvite.serverUrls`'s own doc comment). This is this file's own
 *   decoding convention -- `Invite.tsx`/`Users.tsx` (the invite-link
 *   builders, via `@streamarr-tv/domain::buildInviteUrl`) and the backend's
 *   `oauth.rs::encode_servers_param` (which embeds the same bundle shape
 *   into `verification_uri_complete` for device pairing, §6.3) both encode
 *   against it, so a change here must stay in lockstep with those. Chosen
 *   over percent-encoded JSON directly in the query string so the value
 *   never needs further escaping and stays one opaque token; unpadded so
 *   it never contains a `=` a query string would otherwise need to escape.
 * - `server=` (legacy, singular): read as a one-element address list, so
 *   links already generated by -- or cached in -- an out-of-date client
 *   bundle keep working indefinitely. A deliberate backward-compatibility
 *   choice, since TV app bundles are the hardest client surface to force
 *   an update on.
 *
 * `servers=` wins when both are present. Only absolute HTTP(S) addresses
 * are kept (per-entry, not all-or-nothing: one bad address in an otherwise
 * valid bundle does not sink the invite -- "as long as one of them
 * connects, it's fine" is this design's guiding principle throughout), so
 * the sign-up client can never be pointed at an unexpected browser scheme.
 */
export function parseSignupInvite(search: string): SignupInvite | null {
  const params = new URLSearchParams(search);
  const inviteToken = params.get("invite")?.trim();
  if (!inviteToken) return null;

  const bundled = params.get("servers");
  const rawServerUrls: Array<string | null> =
    bundled !== null ? decodeServersParam(bundled) : [params.get("server")];

  const serverUrls = rawServerUrls
    .map(canonicalizeHttpUrl)
    .filter((url): url is string => url !== undefined);
  if (!serverUrls.length) return null;

  return { serverUrls, inviteToken };
}

/** Validates and canonicalises one candidate address; `undefined` if it isn't an absolute HTTP(S) URL. */
function canonicalizeHttpUrl(value: string | null | undefined): string | undefined {
  const trimmed = value?.trim();
  if (!trimmed) return undefined;
  try {
    const parsed = new URL(trimmed);
    if (parsed.protocol !== "http:" && parsed.protocol !== "https:") return undefined;
    return parsed.toString().replace(/\/$/, "");
  } catch {
    return undefined;
  }
}

/**
 * Decodes a `servers=` value into candidate address strings, extracting
 * each `{peer_node_id, url}` entry's `url` and dropping `peer_node_id` --
 * this file has no use for it (see `SignupInvite.serverUrls`'s own doc
 * comment). Never throws -- malformed base64url, malformed JSON, or a
 * non-array payload all decode to `[]` (which `parseSignupInvite` then
 * treats as "no valid addresses", rather than silently falling back to a
 * legacy `server=` that a link carrying `servers=` shouldn't need anyway).
 * Per-entry, not all-or-nothing: an entry that isn't a well-formed
 * `{url: string}` object is dropped on its own, same leniency
 * `canonicalizeHttpUrl` below applies to the resulting URL strings.
 */
function decodeServersParam(value: string): string[] {
  try {
    const parsed: unknown = JSON.parse(base64UrlDecode(value));
    if (!Array.isArray(parsed)) return [];
    return parsed.map(extractUrl).filter((url): url is string => url !== undefined);
  } catch {
    return [];
  }
}

/** Extracts the `url` field off one `servers=` entry (`{peer_node_id, url}`); `undefined` if the entry isn't a well-formed object with a string `url`. Mirrors `@streamarr-tv/device-auth`'s `serverAddressBundle.ts::decodeServersParam`'s identical extraction. */
function extractUrl(entry: unknown): string | undefined {
  if (entry === null || typeof entry !== "object") return undefined;
  const url = (entry as Record<string, unknown>).url;
  return typeof url === "string" ? url : undefined;
}

/** Mirrors `@streamarr-tv/device-auth`'s `jwt.ts::base64UrlDecode` (unexported there, so duplicated rather than reached into another package's internals for one helper). */
function base64UrlDecode(segment: string): string {
  const base64 = segment.replace(/-/g, "+").replace(/_/g, "/");
  const padded = base64.padEnd(base64.length + ((4 - (base64.length % 4)) % 4), "=");
  if (typeof atob !== "function") {
    throw new Error("This runtime cannot decode base64url values");
  }
  const bytes = Uint8Array.from(atob(padded), (character) => character.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}
